### ISSUE TITLE
Typo pravidla

### ISSUE THREAD

**Issue by mohwald** [JindrazPrahy/DvojkarkyZpevnik#16]
[Typo pravidla](https://github.com/JindrazPrahy/DvojkarskyZpevnik/blob/master/Typo_pravidla.txt) si nikdo neprecte. Patri to do [CONTRIBUTE.md](https://github.com/JindrazPrahy/DvojkarskyZpevnik/blob/master/CONTRIBUTE.md)

**Comment by JindrazPrahy** [comment]
Provedeno.
