### ISSUE TITLE
Špatné formátování dlouhých songů

### ISSUE THREAD

**Issue by mohwald** [JindrazPrahy/DvojkarkyZpevnik#5]
Když zkusím prodloužit např. Do Ameriky (nevejde se na jednu stránku), z 1. strany to zmizí a snaží se to zůstat narvaný na další straně.

**Comment by mohwald** [comment]
Možná řešení:
- Předefinovat velikost u konkrétního songu tak, aby byl akorát velký na stranu
- Přidat více možných sloupců!!!
- Něco jiného...

**Comment by JindrazPrahy** [comment]
Více možných sloupců pomocí minipage je fix, který funguje.
